/*
 * Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
 * By starting with 1 and 2, the first 10 terms will be:
 *
 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 * 
 * By considering the terms in the Fibonacci sequence whose values do not
 * exceed four million, find the sum of the even-valued terms.
 *
 */
public class problem_002 {

	/*
	 * I'm choosing to use the iterative method of the fibonacci sequence
	 */
	public static void main(String[] args){
		int sum = 0;
		
		int prev1 = 1; //the first starting number of the fib sequence
		int prev2 = 1; //the second starting number
		
		while(prev2 < 4000000){
			//advance the fibonacci sequence
			int next = prev1 + prev2;
			prev1 = prev2;
			prev2 = next;
			
			if(next % 2 == 0){ //if it's even
				sum += next;
			}
		}
		
		System.out.println(sum);
		
	}
	
}
